### ISSUE TITLE
有计划添加密钥登录吗？

### ISSUE THREAD

**Issue by catfishlty** [ychappyman/SSHTGBot#1]
不错的项目，方便管理Serv00机器，他家的机器在Next-Terminal上都不能登录。
- 使用PublicKey登录服务器
- 另外简易能够以列表形式显示ssh连接方便一件连接

Exp:
```
> /list

> /ssh user1 hostname1.com
> /ssh user2 hostname2.com
> ...

> /ssh user1

> 连接到 user1@hostname1.com...
```

**Comment by ychappyman** [comment]
非常好的建议，render中可以在/etc/secrets/中存放私钥，这样ACCOUTS_JSON中加一个参数SecretKey对应render路径名称，ssh时先看有没有SecretKey，如果有SecretKey，直接私钥连接。实现起来应该挺简单，周末抽空搞一下，感谢建议~

**Comment by ychappyman** [comment]
resolved
